### ISSUE TITLE
populate user object w/ input form data

### ISSUE THREAD

**Issue by abreaw** [TheCoolKidsUNC/DateNightApp#17]

**Comment by esharri2** [comment]
@reharka I'm going to write a little function to validate the input if the user chooses to type their own stuff (let me know if you've already done that)

**Comment by esharri2** [comment]
Here's a function to validate the user's input if they choose to type their own stuff instead of using the drop down. You can pass it one of the validation arrays (e.g. `validationData.genres`) and the user's input. It will return a trimmed lowercase version of the input if it's valid, or false if it's not. Maybe just copy and paste into your branch if you need this?

```
var validateInput = function(validationArray, input) {
var cleanInput = input.toLowerCase().trim()
if (validationArray.includes(cleanInput)) {
return cleanInput;
}

else {
return false;

	}
}
```

**Comment by ghost** [comment]
Thank you!

**Comment by esharri2** [comment]
@abreaw should we close this? I think this feature is complete, minus validation, and we have separate issue for that.

**Comment by esharri2** [comment]
I think this is working
